# Generated by Django 2.1.5 on 2020-02-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200208_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expired_event',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
