# Generated by Django 2.1.5 on 2020-02-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_expired_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expired_event',
            field=models.BooleanField(default=False),
        ),
    ]
