# Generated by Django 2.1.5 on 2020-02-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200213_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prova',
            field=models.BooleanField(default=True),
        ),
    ]
