# Generated by Django 2.1.5 on 2020-02-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='prova',
        ),
    ]
