# Generated by Django 2.1.5 on 2020-02-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200213_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expired_event',
            field=models.CharField(default='false', max_length=7),
        ),
    ]
