# Generated by Django 2.1.5 on 2020-02-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200213_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expired_event',
            field=models.BooleanField(default=False),
        ),
    ]
